name: publish to nuget

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:    
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: 6.0.x

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Test
      run: dotnet test -c Release --no-restore --no-build --verbosity normal
    
    - name: Pack Abstractions
      run: dotnet pack Codeit.NetStdLibrary.Base.Abstractions/Codeit.NetStdLibrary.Base.Abstractions.csproj -c Release --no-restore --no-build -o .

    - name: Publish Abstractions
      run: dotnet nuget push *.nupkg --skip-duplicate -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}}

    - name: Pack Base
      run: dotnet pack Codeit.NetStdLibrary.Base/Codeit.NetStdLibrary.Base.csproj -c Release --no-restore --no-build -o .

    - name: Publish Base
      run: dotnet nuget push *.nupkg --skip-duplicate -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}}